bitdriftlabs/shared-core

- bd-pgv/src/proto_validate_test.rs
- bd-test-helpers/src/test_api_server.rs
- bd-time/src/lib.rs
Instead of one being `to_proto` and the other `into_proto`, make them both `into_proto` as they take `self` by value
> name proto conversion extensions more consistently

- Cargo.lock
- Cargo.toml
- bd-hyper-network/Cargo.toml
This removes CI issues for cross compiling in the SDK. We can explicitly enable elsewhere if needed (if we use this again in Pulse.)
> hyper network: move back to ring as the default

- bd-client-stats/src/lib.rs
- bd-events/src/lib.rs
- bd-resource-utilization/src/lib.rs
- bd-runtime/src/runtime.rs
- bd-runtime/src/runtime_test.rs
- bd-workflows/src/engine.rs
By having an associated function generated per flag type we are able to avoid having to rely on type inference when creating standalone watches. This avoids repetitive type declaration when the type would have to otherwise be explicitly specified
Also same a few allocations by storing &'static str in the watch map instead of String
> add a register() function to each runtime flag

- Cargo.lock
- bd-client-stats/src/stats.rs
- bd-client-stats/src/stats_test.rs
- bd-time/Cargo.toml
- bd-time/src/lib.rs
This avoids syncing a large fleet if the intervals change.
Fixes BIT-3820
> client stats: jitter interval updates

- Cargo.lock
- Cargo.toml
- bd-api/Cargo.toml
- bd-api/src/api.rs
- bd-api/src/api_test.rs
- bd-client-common/Cargo.toml
- bd-client-common/src/file.rs
- bd-client-common/src/lib.rs
- bd-client-common/src/zlib.rs
- bd-client-stats/Cargo.toml
- bd-client-stats/src/stats.rs
- bd-grpc-codec/src/coding_test.rs
- bd-grpc-codec/src/lib.rs
- bd-logger/src/builder.rs
- bd-proto/src/protos/client/api.rs
- bd-runtime/src/runtime.rs
- bd-runtime/src/runtime_test.rs
- ci/check_license.sh
This is known as the "client kill" mechanism. There are two different paths, both leading to the client being disabled with no network connection to the SaaS for some period of time:
1. The client receives an unauthenticated response.
2. The client receives a specific runtime generic kill update which can be more targeted.
The client will persist a file with a wakeup time after which the client will come back online and attempt to contact the server again.
Fixes BIT-3577
> api: add the ability to remotely shutoff clients

- Cargo.lock
- Cargo.toml
- bd-api/src/api.rs
- bd-api/src/api_test.rs
We want to avoid spinning on error shutdowns so perform backoff if the established connection is less than 1 minute long.
Fixes BIT-3576
> api: backoff on short connections

- bd-grpc/src/axum_helper.rs
- bd-grpc/src/grpc_test.rs
- bd-grpc/src/lib.rs
- bd-test-helpers/src/test_api_server.rs
1) Allow HTTP/2 stream settings to be configured.
2) Add generic read stop functionality to streaming APIs. This allows
callers to use a watch to stop reading from streams and apply back
pressure.
> grpc: reliability functionality

- bd-workflows/src/engine.rs
This uses a simple macro to reduce some of the boilerplate required to track all of the workflow stats after each run.
Also implements Default for WorkflowState instead of an explicit new function
> simplify stats tracking with macro

- Cargo.lock
- Cargo.toml
- bd-api/src/api_test.rs
- bd-client-common/src/error_test.rs
- bd-logger/src/logger.rs
- bd-logger/tests/embedded_logger_integration.rs
- bd-logger/tests/logger_integration.rs
- bd-metadata/src/lib.rs
- bd-test-helpers/src/metadata.rs
We never used "kind" for anything real and this is the first part of officially supporting Electron and also making "apple" and "android" first class platforms.
> transition "kind" to "platform"

- bd-logger/src/builder.rs
- bd-logger/tests/logger_integration.rs
- Rename with_mobile_features to with_client_stats
- Expose the thread/runtime construction to make it easier to reuse the logic from capture-es
- Various small cleanups
> expose thread creation logic from builder + renames

- bd-api/src/api_test.rs
- bd-client-common/src/error_test.rs
- bd-logger/tests/logger_integration.rs
- bd-metadata/src/lib.rs
- bd-test-helpers/src/metadata.rs
This should make it less likely that we forget to include it in the future
> move device_id to top level metadata values

- bd-logger/tests/logger_integration.rs
- bd-workflows/src/engine.rs
- bd-workflows/src/engine_test.rs
- bd-workflows/src/sankey_diagram.rs
This persists the pending Sankey path upload in the workflow state, allowing the SDK to attempt uploading the Sankey path after coming back after shutting down while there were pending uploads. This should let us handle cases where we shut down soon after the Sankey path is completed
Fixes BIT-4463
> persist pending sankey path uploads to workflow state file

- bd-client-common/src/fb.rs
- bd-log-primitives/src/lib.rs
- bd-logger/src/async_log_buffer.rs
- bd-logger/src/async_log_buffer_test.rs
- bd-logger/src/bounded_buffer/size.rs
- bd-logger/src/builder.rs
- bd-logger/src/device_id.rs
- bd-logger/src/internal_report.rs
- bd-logger/src/lib.rs
- bd-logger/src/network.rs
- bd-logger/src/network_test.rs
- bd-logger/tests/logger_integration.rs
- bd-session-replay/src/lib.rs
- bd-session-replay/src/recorder_test.rs
Adds _device_id as a matching field on all logs. This should make it possible to write a matcher against device IDs without us having to upload the ID for each log
BIT-4565
> add device_id as a matching field

- bd-buffer/src/ring_buffer_test.rs
- bd-logger/src/test/crash_handler_integration.rs
- bd-logger/src/test/logger_integration.rs
- bd-logger/src/test/setup.rs
- bd-test-helpers/src/test_api_server.rs
- bd-test-helpers/src/test_api_server/log_upload.rs
Instead of using a number of free functions that take &[u8], instead we have the log upload test helpers return a newtype that wraps the data. This allows us to move all the helpers to take &self which makes them easier to discover via IDEs and the code a bit easier to follow
> improve ergonomics when matching against uploaded logs in test

- bd-crash-handler/Cargo.toml
- bd-crash-handler/src/monitor_test.rs
2024 forces updates to the rust version in capture-sdk, downgrade for now
> use rust edition 2021 for bd-crash-handler

- bd-test-helpers/src/test_api_server.rs
In the platform tests we marshal the stream as an integer into platform code, this should allow us to convert it back to a StreamHandle
> allow creating a StreamHandle from a raw stream_id and server handle

- Cargo.lock
- bd-crash-handler/Cargo.toml
- bd-crash-handler/src/lib.rs
- bd-crash-handler/src/monitor_test.rs
- bd-log-primitives/src/lib.rs
- bd-logger/src/async_log_buffer.rs
- bd-logger/src/async_log_buffer_test.rs
- bd-logger/src/builder.rs
- bd-logger/src/test/crash_handler_integration.rs
- bd-logger/src/test/logger_integration.rs
- bd-logger/src/test/setup.rs
- bd-session/src/activity_based.rs
- bd-session/src/fixed.rs
- bd-test-helpers/src/session.rs
- bd-test-helpers/src/workflow.rs
For crash handling we'll assume that any of the newly reported crashes are associated with the previous process run. This seems sane since we clean up all the crash reports on each start immediately, thus we'd have previously cleaned up any older reports. Since we only check for reports on startup this also means that the current session cannot have emitted this. 
To achieve the correct ordering, we introduce the idea of "initial logs" that are passed to the pre-config buffer that will be replayed after the initial config log but before any of the otherwise queued up logs. This ensures that the crash logs are the first logs processed during app start if they exist, allowing them to be associated with the correct session/workflow engine instance. 
Fixes BIT-4827
> report crash reports with session of previous process

- Cargo.lock
- bd-crash-handler/Cargo.toml
- bd-crash-handler/src/lib.rs
- bd-logger/src/builder.rs
- bd-logger/src/test/crash_handler_integration.rs
Attempts to look for {timestamp}_ at the start of the crash file,
emitting this as the timestamp if parsing succeeded
> extract timestamp from start of crash artifact

- bd-log-metadata/src/lib.rs
- bd-log-primitives/src/lib.rs
- bd-logger/src/async_log_buffer.rs
- bd-logger/src/async_log_buffer_test.rs
- bd-logger/src/bounded_buffer/size.rs
- bd-logger/src/device_id.rs
- bd-logger/src/internal_report.rs
- bd-logger/src/lib.rs
- bd-logger/src/logger.rs
- bd-logger/src/metadata.rs
- bd-logger/src/metadata_test.rs
- bd-logger/src/network.rs
- bd-logger/src/network_test.rs
- bd-logger/src/test/crash_handler_integration.rs
- bd-logger/src/test/embedded_logger_integration.rs
- bd-logger/src/test/logger_integration.rs
- bd-test-helpers/src/metadata_provider.rs
This fixes a regression from the change to use a map where custom fields
could now override ootb fields
> use two distinct maps for custom and ootb logs 

- bd-crash-handler/src/lib.rs
- bd-workflows/src/workflow.rs
This can happen if a field extraction does not
extract anything.
> workflow: remove sankey debug assert

- bd-logger/src/consumer_test.rs
- bd-logger/src/test/crash_handler_integration.rs
- bd-test-helpers/src/test_api_server.rs
- bd-test-helpers/src/test_api_server/log_upload.rs
- Handle the case where the log uploads get split between uploads in the crash test
- Reduce the number of logs we use for the old log test to minimize risk of buffer overflow
> deflake crash integration test and old logs test

- bd-logger/src/test/setup.rs
- bd-workflows/src/engine.rs
- bd-workflows/src/engine_test.rs
When we added compression/CRC to the state file, this causes a crash if the library is downgraded as bincode is not very resilient. We will look at no longer using bincode in a future version.
> workflows: bump state file name

- bd-api/src/api.rs
- bd-api/src/api_test.rs
- bd-client-common/src/payload_conversion.rs
- bd-client-common/src/safe_file_cache.rs
- bd-logger/src/builder.rs
- bd-logger/src/client_config.rs
- bd-logger/src/test/logger_integration.rs
- bd-logger/src/test/setup.rs
- bd-runtime/src/runtime.rs
This moves runtime config loading to the very beginning of the future exectued on the tokio thread. This should allow us to read runtime flags super early on without having to worry about racing with the api task that would previously handle initialization.
Also cleans up some of the tech debt around configuration pipelines that remained from a previous attempt at supporting multiple configuration pipelines
Fixes BIT-5408
> load runtime config from disk as early as possible

- bd-crash-handler/src/lib.rs
- bd-crash-handler/src/monitor_test.rs
- bd-log-primitives/src/lib.rs
- bd-logger/src/builder.rs
- bd-logger/src/test/crash_handler_integration.rs
Updating FatalIssue Log contents depending on mechanism type
Frontend changes added in https://github.com/bitdriftlabs/bitdrift-frontend/pull/2298
More details in https://docs.google.com/document/d/1JTlIW2rB_3crYArBB6wHeF0JGdTPA6DrAnFCw3Jo8DM/edit?tab=t.p3ma0bg1t9cz#heading=h.odruallazj53 
| Field/Value change | Integration | BuiltIn |
| --------------------| -----------| ---------|
| **details_key** | _crash_details | _app_exit_details |
| **reason_key** | _crash_reason | _app_exit_info |
| **message_value** | App crashed | AppExit |
For matching with existing `Fatal Issue -JVM` workflows we are relying on '_app_exit_reason = Crash'
NOTE: This requires to also update frontend and update iOS client to append the report type to file name …
> [FatalIssueReporter] Update FatalIssue log depending on mechanism

- bd-grpc/Cargo.toml
- bd-grpc/build.rs
- bd-grpc/src/error.rs
- bd-grpc/src/generated/proto/mod.rs
- bd-grpc/src/generated/proto/test.rs
- bd-grpc/src/grpc_test.rs
- bd-grpc/src/lib.rs
- bd-grpc/src/proto/test.proto
Previously these errors were always returned as gRPC errors.
Fixes BIT-5344
> grpc: make sure bad request errors are returned as connect errors

- bd-api/src/api.rs
- bd-api/src/api_test.rs
- bd-client-stats/src/stats.rs
- bd-client-stats/src/stats_test.rs
- bd-logger/src/builder.rs
- bd-logger/src/log_replay.rs
- bd-logger/src/logger.rs
- bd-logger/src/logger_test.rs
- bd-logger/src/logging_state.rs
- bd-logger/src/test/crash_handler_integration.rs
- bd-logger/src/test/embedded_logger_integration.rs
- bd-logger/src/test/logger_integration.rs
- bd-logger/src/test/setup.rs
- bd-proto/src/protos/client/api.rs
- bd-runtime/src/runtime.rs
- bd-test-helpers/src/test_api_server.rs
- profiling/src/main.rs
During sleep mode the stats upload interval is greatly reduced. Everything else is unchanged currently. Analytics about the mode are sent at handshake start as well as within each ping.
Fixes BIT-5059
> implement initial sleep mode support

- Cargo.lock
- bd-completion/Cargo.toml
- bd-completion/src/lib.rs
- bd-logger/src/async_log_buffer.rs
Resolves BIT-4913
This follow similar approach from @snowp in https://github.com/bitdriftlabs/shared-core/pull/125 and moves the time out logic as part of bd_completion
To avoid potentially blocking permanently on no network situations upon logger blocking calls adding timeout to those calls
[See related doc](https://docs.google.com/document/d/1weR9GFGcvX-RLJd47KRMmhfg2ZknJc7mpUiCEaJvdM8/edit?tab=t.0)
Steps
0. Run Android gradle test app
1. Set app in airplane mode
2. Trigger artificial crash
3. App will continue crashing after the defined thresholds (4seconds) to avoid ANRs on android. Before will be deadlocked an leading to ANR dialog
See demo here https://drive.google.com/file/d/12ui3gyApvHdl37YGi4V6-36K-ZL41MQ0/view?usp=drive_link
```
06-17 15:46:10.449  9324  9324 D …
```
> Adding blocking_recv_with_timeout

- bd-buffer/src/ring_buffer_test.rs
- bd-client-stats-store/src/lib.rs
- bd-client-stats-store/src/lib_test.rs
- bd-client-stats-store/src/test/mod.rs
- bd-client-stats/src/lib.rs
- bd-client-stats/src/stats.rs
- bd-stats-common/src/lib.rs
- bd-test-helpers/src/stats.rs
- bd-workflows/src/config.rs
- bd-workflows/src/metrics.rs
- bd-workflows/src/metrics_test.rs
- bd-workflows/src/workflow_test.rs
This can actually happen currently.
Fixes BIT-5714
> client stats: do not panic if a metric changes type

- bd-runtime/src/runtime.rs
- bd-workflows/src/engine.rs
- bd-workflows/src/engine_test.rs
- bd-workflows/src/workflow.rs
- bd-workflows/src/workflow_test.rs
1) "workflows.state_periodic_write_interval_ms": This flag is redundant
as we do periodic persistence processing on every log processed and
logs are received frequently.
2) "workflows.traversals_global_count_limit": With the removal of
parallel execution mode this flag doesn't provide a lot of value and
removing it cleans up a lot of complexity.
Also clean up some metrics that I don't think provide any real operational value.
> workflows: cleanup 2 runtime flags

- bd-logger/src/consumer.rs
- bd-logger/src/consumer_test.rs
- bd-runtime/src/runtime.rs
Allow batching streamed logs in the case where multiple logs are enqueued back to back
> Improve bd tail streaming throughput

- bd-bonjson-tests/src/ffi_tests.rs
- bd-bonjson/src/decoder.rs
- bd-bonjson/src/decoder_test.rs
- bd-bonjson/src/encoder.rs
- bd-bonjson/src/encoder_test.rs
- bd-bonjson/src/lib.rs
- bd-bonjson/src/writer.rs
- fuzz/fuzz_targets/bonjson.rs
* Removed `Value::None` because it was only being used to signal a failure to get a value
* Moved `Value` to the library level so that it works much like `Value` does in JSON serde
* Hid the `Decoder` struct and changed the decoder public interface to only one function: `decode`
* Added a matching `encode` function that fills a vector, and an `encode_into` function that fills a slice
This is an API breaking change that will require updates in capture-sdk (which I'll do in parallel).
> Add a BONJSON encoder and harmonize the general API

- bd-api/src/api.rs
- bd-api/src/api_test.rs
- bd-artifact-upload/src/uploader_test.rs
- bd-client-common/src/lib.rs
- bd-client-common/src/payload_conversion.rs
- bd-client-common/src/safe_file_cache.rs
- bd-client-stats/src/stats_test.rs
- bd-crash-handler/src/config_writer_test.rs
- bd-crash-handler/src/monitor_test.rs
- bd-events/src/listener_test.rs
- bd-grpc-codec/src/code.rs
- bd-grpc-codec/src/lib.rs
- bd-grpc/src/client.rs
- bd-grpc/src/connect_protocol.rs
- bd-grpc/src/error.rs
- bd-grpc/src/lib.rs
- bd-grpc/src/status.rs
- bd-logger/src/async_log_buffer_test.rs
- bd-logger/src/builder.rs
- bd-logger/src/client_config.rs
- bd-logger/src/client_config_test.rs
- bd-logger/src/consumer_test.rs
- bd-logger/src/ratelimit_test.rs
- bd-proto/src/protos/client/api.rs
- bd-resource-utilization/src/reporter_test.rs
- bd-runtime/src/runtime.rs
- bd-runtime/src/runtime_test.rs
- bd-session-replay/src/recorder_test.rs
- profiling/src/main.rs
1) Remove shutdown handling in the API. It makes the code convoluted and
doesn't do anything useful. Instead just move the shutdown wait to
the top level future.
2) Add retry after handling in the API.
3) Move gRPC Code to the codec crate so it can be used in client code. 
4) Some cleanups in order to remove a bunch of clones during config
processing.
Fixes BIT-5835
> api: implement better rate limiting backoff

- Cargo.lock
- Cargo.toml
- bd-api/src/api.rs
- bd-api/src/api_test.rs
- bd-artifact-upload/src/uploader.rs
- bd-artifact-upload/src/uploader_test.rs
- bd-client-common/Cargo.toml
- bd-client-common/src/file.rs
- bd-client-common/src/file_test.rs
- bd-client-common/src/lib.rs
- bd-client-common/src/safe_file_cache.rs
- bd-client-common/src/safe_file_cache_test.rs
- bd-client-stats/src/stats_test.rs
- bd-crash-handler/src/config_writer_test.rs
- bd-crash-handler/src/monitor_test.rs
- bd-events/src/listener_test.rs
- bd-logger/src/async_log_buffer_test.rs
- bd-logger/src/builder.rs
- bd-logger/src/client_config.rs
- bd-logger/src/client_config_test.rs
- bd-logger/src/consumer_test.rs
- bd-logger/src/ratelimit_test.rs
- bd-resource-utilization/src/reporter_test.rs
- bd-runtime/src/runtime.rs
- bd-runtime/src/runtime_test.rs
- bd-runtime/src/test.rs
- bd-session-replay/src/recorder_test.rs
- profiling/src/main.rs
Now we store the nonce of the last accepted/cached configuration. If we think we have entered a crash loop, we refuse to receive new configuration unless the nonce has changed. In order to support this we no longer clean the cached files when we hit the retry count. The downside of this is that if a client is put into the killed state it would likely come back online and refuse to accept new config if the config hasn't changed. To handle this case we clear cached config when the client enters the killed state.
Fixes BIT-6168
> improved runtime/workflow crash loop detection

- bd-logger/src/async_log_buffer.rs
Something during shutdown is dropping the blocking log receiver. It's not worth fixing this right now.
> fix flake in previous PR

- BENCHMARKS.md
- Cargo.lock
- Cargo.toml
- README.md
- bd-client-common/src/init_lifecycle.rs
- bd-proto/src/flatbuffers/buffer_log_generated.h
- bd-proto/src/flatbuffers/buffer_log_generated.rs
- bd-proto/src/flatbuffers/common_generated.h
- bd-proto/src/flatbuffers/common_generated.rs
- bd-proto/src/flatbuffers/report_generated.rs
- bd-report-convert/src/flatbuffers/common_generated.h
- bd-report-convert/src/flatbuffers/report_generated.h
- bd-workflows/Cargo.toml
- bd-workflows/benches/linux_only/matcher.rs
- bd-workflows/benches/linux_only/mod.rs
- bd-workflows/benches/main.rs
- bd-workspace-hack/Cargo.toml
This provides much more accurate data for this type of benchmark, with the caveat that it's only runnable on Linux (so requires a linux VM when working on a Mac).
> workflow benchmarks: switch to callgrind

- bd-log-primitives/src/lib.rs
- bd-log/src/rate_limit_log.rs
- bd-logger/src/async_log_buffer.rs
- bd-logger/src/async_log_buffer_test.rs
- bd-logger/src/internal.rs
- bd-logger/src/log_replay.rs
- bd-logger/src/logger.rs
- bd-logger/src/logger_test.rs
- bd-logger/src/test/crash_handler_integration.rs
- bd-logger/src/test/embedded_logger_integration.rs
- bd-logger/src/test/logger_integration.rs
- bd-logger/src/test/setup.rs
- bd-test-helpers/src/test_api_server/log_upload.rs
- logger-cli/src/logger.rs
- Rework feature flag initialization to not require a mutex and fail permanently in the case of disk issues
- Use a &'static str for the CaptureSession string to save an allocation
- Remove initial_logs from async_log_buffer, no longer used
- Add macro for repeated reentrancy logic in logger.rs
> various cleanups 
